change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
exclude-labels:
  - "release-drafter-ignore"
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/ludeeus/awesomeversion/compare/$PREVIOUS_TAG...$RESOLVED_VERSION